import type { GrupoObjetivos } from '@/services/gruposService';

type PlanificacionNavigationUiReset = {
    setSearchTerm: (value: string) => void;
    setShowGuardiaSearch: (value: boolean) => void;
    setPinnedExternalEmpIds: (value: Set<string>) => void;
    setForceShowAll: (value: boolean) => void;
    setDotacionPoolSearch: (value: string) => void;
    setSelection: (value: { start: null; end: null }) => void;
    setComparingSnapshot: (value: null) => void;
    setOpenDrop: (value: null) => void;
    setAutoGeneratedReady: (value: boolean) => void;
};

function resetPlanificacionNavigationUi({
    setSearchTerm,
    setShowGuardiaSearch,
    setPinnedExternalEmpIds,
    setForceShowAll,
    setDotacionPoolSearch,
    setSelection,
    setComparingSnapshot,
    setOpenDrop,
    setAutoGeneratedReady,
}: PlanificacionNavigationUiReset): void {
    setSearchTerm('');
    setShowGuardiaSearch(false);
    setPinnedExternalEmpIds(new Set());
    setForceShowAll(false);
    setDotacionPoolSearch('');
    setSelection({ start: null, end: null });
    setComparingSnapshot(null);
    setOpenDrop(null);
    setAutoGeneratedReady(false);
}

function confirmDiscardPendingChanges(pendingChanges: Record<string, unknown>): boolean {
    if (Object.keys(pendingChanges).length === 0) return true;
    return confirm('⚠️ TIENES CAMBIOS SIN GUARDAR.\n¿Descartar y cambiar de objetivo?');
}

export type ApplyPlanificacionContextChangeParams = PlanificacionNavigationUiReset & {
    newClient: string;
    newObjective: string;
    pendingChanges: Record<string, unknown>;
    setPendingChanges: (value: Record<string, never>) => void;
    setPendingNovedades: (value: Record<string, never>) => void;
    clearUndoStack: () => void;
    setSelectedGrupo: (value: null) => void;
    setSelectedClient: (value: string) => void;
    setSelectedObjective: (value: string) => void;
};

export function applyPlanificacionContextChange({
    newClient,
    newObjective,
    pendingChanges,
    setPendingChanges,
    setPendingNovedades,
    clearUndoStack,
    setSelectedGrupo,
    setSelectedClient,
    setSelectedObjective,
    ...uiReset
}: ApplyPlanificacionContextChangeParams): void {
    if (!confirmDiscardPendingChanges(pendingChanges)) return;
    if (Object.keys(pendingChanges).length > 0) {
        setPendingChanges({});
        setPendingNovedades({});
        clearUndoStack();
    }
    setSelectedGrupo(null);
    setSelectedClient(newClient);
    setSelectedObjective(newObjective);
    resetPlanificacionNavigationUi(uiReset);
}

export type ApplyPlanificacionGrupoChangeParams = PlanificacionNavigationUiReset & {
    grupo: GrupoObjetivos | null;
    pendingChanges: Record<string, unknown>;
    setPendingChanges: (value: Record<string, never>) => void;
    setPendingNovedades: (value: Record<string, never>) => void;
    setSelectedGrupo: (value: GrupoObjetivos | null) => void;
    setGrupoUnifiedMode: (value: boolean) => void;
    setSelectedClient: (value: string) => void;
    setSelectedObjective: (value: string) => void;
};

export function applyPlanificacionGrupoChange({
    grupo,
    pendingChanges,
    setPendingChanges,
    setPendingNovedades,
    setSelectedGrupo,
    setGrupoUnifiedMode,
    setSelectedClient,
    setSelectedObjective,
    ...uiReset
}: ApplyPlanificacionGrupoChangeParams): void {
    if (!confirmDiscardPendingChanges(pendingChanges)) return;
    if (Object.keys(pendingChanges).length > 0) {
        setPendingChanges({});
        setPendingNovedades({});
    }
    setSelectedGrupo(grupo);
    setGrupoUnifiedMode(true);
    if (grupo && grupo.objectiveIds.length > 0) {
        setSelectedClient(grupo.clientId);
        setSelectedObjective(grupo.objectiveIds[0]);
    } else {
        setSelectedClient('');
        setSelectedObjective('');
    }
    resetPlanificacionNavigationUi(uiReset);
}
