"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.esFeriadoConCobertura = exports.fechasFeriadosConCobertura = exports.feriadosConCobertura = exports.inferirCoberturaFeriados = exports.proponer12hEquivalente = exports.esBandaDe12h = exports.detectarBandasEspeciales = exports.detectarEstadoDesdeMemoria = exports.detectarEstadoServicio = exports.hayDeficit = exports.generarAlertasDeficit = exports.calcularMinimoParaBanda = exports.calcularMasaCritica = exports.agruparNeedsPorBanda = exports.filtrarNeedsParaFecha = exports.leerSlaYDerivarCobertura = void 0;
var s1_leer_sla_1 = require("./s1-leer-sla");
Object.defineProperty(exports, "leerSlaYDerivarCobertura", { enumerable: true, get: function () { return s1_leer_sla_1.leerSlaYDerivarCobertura; } });
Object.defineProperty(exports, "filtrarNeedsParaFecha", { enumerable: true, get: function () { return s1_leer_sla_1.filtrarNeedsParaFecha; } });
Object.defineProperty(exports, "agruparNeedsPorBanda", { enumerable: true, get: function () { return s1_leer_sla_1.agruparNeedsPorBanda; } });
var s2_masa_critica_1 = require("./s2-masa-critica");
Object.defineProperty(exports, "calcularMasaCritica", { enumerable: true, get: function () { return s2_masa_critica_1.calcularMasaCritica; } });
Object.defineProperty(exports, "calcularMinimoParaBanda", { enumerable: true, get: function () { return s2_masa_critica_1.calcularMinimoParaBanda; } });
Object.defineProperty(exports, "generarAlertasDeficit", { enumerable: true, get: function () { return s2_masa_critica_1.generarAlertasDeficit; } });
Object.defineProperty(exports, "hayDeficit", { enumerable: true, get: function () { return s2_masa_critica_1.hayDeficit; } });
var s3_detectar_estado_1 = require("./s3-detectar-estado");
Object.defineProperty(exports, "detectarEstadoServicio", { enumerable: true, get: function () { return s3_detectar_estado_1.detectarEstadoServicio; } });
Object.defineProperty(exports, "detectarEstadoDesdeMemoria", { enumerable: true, get: function () { return s3_detectar_estado_1.detectarEstadoDesdeMemoria; } });
var s4_bandas_especiales_1 = require("./s4-bandas-especiales");
Object.defineProperty(exports, "detectarBandasEspeciales", { enumerable: true, get: function () { return s4_bandas_especiales_1.detectarBandasEspeciales; } });
Object.defineProperty(exports, "esBandaDe12h", { enumerable: true, get: function () { return s4_bandas_especiales_1.esBandaDe12h; } });
Object.defineProperty(exports, "proponer12hEquivalente", { enumerable: true, get: function () { return s4_bandas_especiales_1.proponer12hEquivalente; } });
var s5_cobertura_feriados_1 = require("./s5-cobertura-feriados");
Object.defineProperty(exports, "inferirCoberturaFeriados", { enumerable: true, get: function () { return s5_cobertura_feriados_1.inferirCoberturaFeriados; } });
Object.defineProperty(exports, "feriadosConCobertura", { enumerable: true, get: function () { return s5_cobertura_feriados_1.feriadosConCobertura; } });
Object.defineProperty(exports, "fechasFeriadosConCobertura", { enumerable: true, get: function () { return s5_cobertura_feriados_1.fechasFeriadosConCobertura; } });
Object.defineProperty(exports, "esFeriadoConCobertura", { enumerable: true, get: function () { return s5_cobertura_feriados_1.esFeriadoConCobertura; } });
//# sourceMappingURL=index.js.map