import * as functions from 'firebase-functions';
export declare const createUser: functions.HttpsFunction & functions.Runnable<any>;
export declare const scheduleShift: functions.HttpsFunction & functions.Runnable<any>;
export declare const manageShifts: functions.HttpsFunction & functions.Runnable<any>;
export declare const auditShift: functions.HttpsFunction & functions.Runnable<any>;
export declare const manageData: functions.HttpsFunction & functions.Runnable<any>;
export declare const manageHierarchy: functions.HttpsFunction & functions.Runnable<any>;
export declare const manageEmployees: functions.HttpsFunction & functions.Runnable<any>;
export declare const manageSystemUsers: functions.HttpsFunction & functions.Runnable<any>;
export declare const manageAbsences: functions.HttpsFunction & functions.Runnable<any>;
export declare const managePatterns: functions.HttpsFunction & functions.Runnable<any>;
export declare const manageAgreements: functions.HttpsFunction & functions.Runnable<any>;
export declare const checkSystemHealth: functions.HttpsFunction & functions.Runnable<any>;
export declare const crearUsuarioSistema: functions.HttpsFunction & functions.Runnable<any>;
export declare const limpiarBaseDeDatos: functions.HttpsFunction & functions.Runnable<any>;
export declare const requestCheckIn: functions.HttpsFunction & functions.Runnable<any>;
export declare const registrarFichadaManual: functions.HttpsFunction & functions.Runnable<any>;
export declare const reportarAusencia: functions.HttpsFunction & functions.Runnable<any>;
export declare const createPortalAccess: functions.HttpsFunction & functions.Runnable<any>;
export declare const createClientPortalAccess: functions.HttpsFunction & functions.Runnable<any>;
export { onNovedadCreated } from './notifications/onNovedadCreated';
export { onTurnoWrite } from './notifications/onTurnoWrite';
export { payrollApi } from './payroll-api/handler';
export declare const sendTestNotification: functions.HttpsFunction & functions.Runnable<any>;
export declare const autoCompletarTurnos: functions.CloudFunction<unknown>;
export declare const detectarAusencias: functions.CloudFunction<unknown>;
export declare const gestionarVacantes: functions.CloudFunction<unknown>;
export declare const triggerBackup: functions.HttpsFunction & functions.Runnable<any>;
export declare const restoreBackup: functions.HttpsFunction & functions.Runnable<any>;
export declare const onAusenciaCreatedFromPortal: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const scheduledBackup: functions.CloudFunction<unknown>;
