const fs = require('fs');
const path = require('path');

const baseDir = path.join(__dirname, 'src', 'pages', 'admin', 'planificacion', 'auditplan');
if (!fs.existsSync(baseDir)) fs.mkdirSync(baseDir, { recursive: true });

function write(name, lines) {
    fs.writeFileSync(path.join(baseDir, name), lines.join('\n').trim());
    console.log('✅ ' + name + ' REPARADO.');
}

// 1. CONSTANTS.TS
write('constants.ts', [
    "export const SHIFT_STYLES: any = {",
    "    'M': 'bg-blue-100 text-blue-700 border-blue-200', 'T': 'bg-orange-100 text-orange-700 border-orange-200',",
    "    'N': 'bg-indigo-100 text-indigo-700 border-indigo-200', 'D12': 'bg-cyan-100 text-cyan-700 border-cyan-200',",
    "    'N12': 'bg-purple-100 text-purple-700 border-purple-200', 'F': 'bg-emerald-100 text-emerald-700 border-emerald-200',",
    "    'PU': 'bg-pink-100 text-pink-700 border-pink-200', 'A': 'bg-red-100 text-red-700 border-red-300 font-black',",
    "    'V': 'bg-teal-600 text-white border-teal-700 font-black shadow-sm', 'L': 'bg-purple-100 text-purple-700 border-purple-300 font-black',",
    "    'E': 'bg-rose-100 text-rose-700 border-rose-300 font-black', 'AA': 'bg-amber-100 text-amber-700 border-amber-300',",
    "    'PAST': 'bg-gray-100 text-gray-300 border-gray-200 cursor-not-allowed', 'C': 'bg-slate-100 text-slate-600 border-slate-300 font-bold opacity-90',",
    "    'FT': 'bg-violet-600 text-white border-violet-700 font-black shadow-sm', 'FF': 'bg-cyan-600 text-white border-cyan-700 font-black shadow-sm',",
    "    'SWAP': 'bg-cyan-50 text-cyan-700 border-cyan-300 border-dashed font-bold'",
    "};",
    "export const SHIFT_HOURS_LOOKUP: any = { 'M': 8, 'T': 8, 'N': 8, 'D12': 12, 'N12': 12, 'PU': 12, 'F': 0, 'FF': 0, 'V': 0, 'L': 0, 'A': 0, 'E': 0, 'AA': 0, 'C': 8 };"
]);

// 2. UTILS.TS
write('utils.ts', [
    "export const getDateKey = (dateInput: any) => {",
    "    const d = dateInput.toDate ? dateInput.toDate() : new Date(dateInput);",
    "    const options: any = { timeZone: 'America/Argentina/Cordoba', year: 'numeric', month: '2-digit', day: '2-digit' };",
    "    const parts = new Intl.DateTimeFormat('es-AR', options).formatToParts(d);",
    "    const day = parts.find((p: any) => p.type === 'day')?.value;",
    "    const month = parts.find((p: any) => p.type === 'month')?.value;",
    "    const year = parts.find((p: any) => p.type === 'year')?.value;",
    "    return year + '-' + month + '-' + day;",
    "};",
    "export const isDateLocked = (dateStr: string) => {",
    "    const parts = dateStr.split('-').map(Number);",
    "    const cellDate = new Date(parts[0], parts[1] - 1, parts[2]);",
    "    cellDate.setHours(23, 59, 59, 999);",
    "    return cellDate < new Date();",
    "};",
    "export const isShiftConsolidated = (shift: any) => shift && ['PRESENT', 'CHECK_IN', 'COMPLETED'].includes(shift.status);",
    "export const getDayLetter = (dateStr: string) => {",
    "    const parts = dateStr.split('-').map(Number);",
    "    return ['D', 'L', 'M', 'X', 'J', 'V', 'S'][new Date(parts[0], parts[1] - 1, parts[2]).getDay()];",
    "};"
]);

// 3. LABORRULES.TS
write('laborRules.ts', [
    "import { getDateKey } from './utils';",
    "import { SHIFT_HOURS_LOOKUP } from './constants';",
    "export const checkLaborRules = (empId: string, targetDate: Date, newHours: number, employees: any[], agreements: any[], pendingChanges: any, shiftsMap: any, absencesMap: any) => {",
    "    const emp = employees.find(e => e.id === empId); if (!emp) return null;",
    "    const key = empId + '_' + getDateKey(targetDate);",
    "    if (absencesMap[key]) return 'ALERTA: Ausencia Registrada.';",
    "    if (shiftsMap[key]?.code === 'F') return 'ALERTA: Franco Asignado.';",
    "    return null;",
    "};"
]);

// 4. SLAINTELLIGENCE.TS
write('slaIntelligence.ts', [
    "import { getDayLetter } from './utils';",
    "import { SHIFT_HOURS_LOOKUP } from './constants';",
    "export const calculateCoverageStats = (dateStr: string, posName: string, structure: any[], emps: any[], changes: any, existing: any, objectiveId: string) => {",
    "    const pos = structure.find(p => p.positionName === posName) || { qty: 1, coverageType: '24hs' };",
    "    const pax = Number(pos.qty) || 1;",
    "    const active = pos.activeDays ? pos.activeDays.includes(getDayLetter(dateStr)) : true;",
    "    let target = active ? (pos.coverageType === '24hs' ? 24 * pax : 8 * pax) : 0;",
    "    let current = 0;",
    "    emps.forEach(emp => {",
    "        const key = emp.id + '_' + dateStr;",
    "        const shift = changes[key] ? (changes[key].isDeleted ? null : changes[key]) : existing[key];",
    "        if (shift && (shift.objectiveId === objectiveId || changes[key])) {",
    "            if (!['F','FF','V','L'].includes(shift.code)) current += (SHIFT_HOURS_LOOKUP[shift.code] || 8);",
    "        }",
    "    });",
    "    return { current, target, pax, active };",
    "};"
]);

// 5. USEPLANIFICACIONLOGIC.TS
write('usePlanificacionLogic.ts', [
    "import { useState, useEffect } from 'react';",
    "import { db } from '@/lib/firebase';",
    "import { collection, onSnapshot, query, where, getDocs, writeBatch, serverTimestamp, Timestamp, doc } from 'firebase/firestore';",
    "import { toast } from 'sonner';",
    "import { getDateKey } from './utils';",
    "export function usePlanificacionLogic(selectedClient: string, selectedObjective: string, operatorName: string) {",
    "    const [employees, setEmployees] = useState<any[]>([]);",
    "    const [shiftsMap, setShiftsMap] = useState<any>({});",
    "    const [absencesMap, setAbsencesMap] = useState<any>({});",
    "    const [clients, setClients] = useState<any[]>([]);",
    "    const [pendingChanges, setPendingChanges] = useState<any>({});",
    "    const [isProcessing, setIsProcessing] = useState(false);",
    "    const [positionStructure, setPositionStructure] = useState<any[]>([]);",
    "    useEffect(() => {",
    "        const unsubE = onSnapshot(collection(db, 'empleados'), snap => setEmployees(snap.docs.map(d => ({ id: d.id, ...d.data(), name: d.data().name || (d.data().firstName + ' ' + d.data().lastName) }))));",
    "        const unsubC = onSnapshot(collection(db, 'clients'), snap => setClients(snap.docs.map(d => ({ id: d.id, ...d.data() }))));",
    "        const unsubS = onSnapshot(collection(db, 'turnos'), snap => {",
    "            const map: any = {};",
    "            snap.docs.forEach(d => { if(d.data().startTime) map[`${d.data().employeeId}_${getDateKey(d.data().startTime)}`] = { id: d.id, ...d.data(), code: d.data().code || d.data().type }; });",
    "            setShiftsMap(map);",
    "        });",
    "        const unsubA = onSnapshot(collection(db, 'ausencias'), snap => {",
    "            const map: any = {};",
    "            snap.docs.forEach(d => { if(d.data().startDate) map[`${d.data().employeeId}_${d.data().startDate}`] = { id: d.id, ...d.data() }; });",
    "            setAbsencesMap(map);",
    "        });",
    "        return () => { unsubE(); unsubC(); unsubS(); unsubA(); };",
    "    }, []);",
    "    useEffect(() => {",
    "        if (!selectedClient || !selectedObjective) return;",
    "        getDocs(query(collection(db, 'servicios_sla'), where('clientId', '==', selectedClient))).then(snap => {",
    "            const srv = snap.docs.map(d => d.data()).find(d => d.objectiveId === selectedObjective);",
    "            if (srv?.positions) setPositionStructure(Array.isArray(srv.positions) ? srv.positions : Object.values(srv.positions));",
    "        });",
    "    }, [selectedClient, selectedObjective]);",
    "    const handleSaveAll = async () => {",
    "        setIsProcessing(true); const batch = writeBatch(db);",
    "        try {",
    "            for (const [key, change] of Object.entries(pendingChanges)) {",
    "                const [empId, dateStr] = key.split('_'); const existing = shiftsMap[key];",
    "                if ((change as any).isDeleted) { if(existing?.id) batch.delete(doc(db, 'turnos', existing.id)); }",
    "                else {",
    "                    if(existing?.id) batch.delete(doc(db, 'turnos', existing.id));",
    "                    const [y, m, d] = dateStr.split('-').map(Number);",
    "                    batch.set(doc(collection(db, 'turnos')), {",
    "                        employeeId: empId, clientId: selectedClient, objectiveId: selectedObjective, code: (change as any).code, startTime: Timestamp.fromDate(new Date(y, m-1, d, 7, 0)), endTime: Timestamp.fromDate(new Date(y, m-1, d, 15, 0)), positionName: (change as any).positionName || 'General', status: 'Assigned', createdAt: serverTimestamp(), actor: operatorName",
    "                    });",
    "                }",
    "            }",
    "            await batch.commit(); setPendingChanges({}); toast.success('Guardado');",
    "        } catch (e) { toast.error('Error'); } finally { setIsProcessing(false); }",
    "    };",
    "    return { employees, shiftsMap, absencesMap, clients, pendingChanges, setPendingChanges, isProcessing, positionStructure, handleSaveAll };",
    "}"
]);

// 6. MODALS.TSX
write('Modals.tsx', [
    "import React from 'react';",
    "import { Trash2, FileText, X } from 'lucide-react';",
    "import { SHIFT_STYLES } from './constants';",
    "export const ShiftSelectorModal = ({ selectedCell, employees, positionStructure, activePosition, setActivePosition, onAssign, onDelete, onRRHH, onClose }: any) => {",
    "    if (!selectedCell) return null;",
    "    const emp = employees.find((e:any) => e.id === selectedCell.empId);",
    "    return (",
    "        <div className='fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm animate-in fade-in' onClick={onClose}>",
    "            <div className='bg-white p-10 rounded-[3rem] w-[500px] shadow-2xl' onClick={e => e.stopPropagation()}>",
    "                <div className='flex justify-between items-center mb-8 border-b pb-4'>",
    "                    <div><h3 className='font-black text-2xl text-slate-800 uppercase'>{emp?.name}</h3><p className='text-xs font-bold text-indigo-500'>{selectedCell.dateStr}</p></div>",
    "                    <button onClick={onDelete} className='p-3 bg-rose-50 text-rose-500 rounded-2xl hover:bg-rose-500 hover:text-white'><Trash2/></button>",
    "                </div>",
    "                <div className='mb-6 bg-slate-50 p-4 rounded-2xl'>",
    "                    <label className='text-[10px] font-black uppercase text-slate-400 block mb-1'>Puesto</label>",
    "                    <select value={activePosition} onChange={e => setActivePosition(e.target.value)} className='w-full p-3 rounded-xl border-2 font-bold'>",
    "                        {positionStructure.map((p: any) => <option key={p.positionName} value={p.positionName}>{p.positionName}</option>)}",
    "                    </select>",
    "                </div>",
    "                <div className='grid grid-cols-4 gap-3 mb-6'>",
    "                    {['M', 'T', 'N', 'F', 'D12', 'N12'].map(code => (",
    "                        <button key={code} onClick={() => onAssign(code)} className={'p-4 rounded-2xl border font-black ' + SHIFT_STYLES[code]}>{code}</button>",
    "                    ))}",
    "                </div>",
    "                <button onClick={onRRHH} className='w-full py-4 bg-slate-900 text-white rounded-2xl font-black flex items-center justify-center gap-3'><FileText size={20}/> RRHH</button>",
    "            </div>",
    "        </div>",
    "    );",
    "};",
    "export const RRHHModal = ({ onSubmit, onClose }: any) => (",
    "    <div className='fixed inset-0 z-[110] flex items-center justify-center bg-black/80 backdrop-blur-md'>",
    "        <div className='bg-white p-10 rounded-[3rem] w-[400px] shadow-2xl'>",
    "            <h3 className='text-2xl font-black uppercase mb-8 border-b pb-4'>Novedad RRHH</h3>",
    "            <button onClick={onSubmit} className='w-full py-4 bg-indigo-600 text-white font-black rounded-2xl mb-4 shadow-lg'>REGISTRAR</button>",
    "            <button onClick={onClose} className='w-full py-2 font-bold text-slate-400'>Cerrar</button>",
    "        </div>",
    "    </div>",
    ");"
]);

// 7. INDEX.TSX (EL FIX REAL DEL LIST)
write('index.tsx', [
    "import React, { useState, useMemo, useEffect } from 'react';",
    "import Head from 'next/head';",
    "import dynamic from 'next/dynamic';",
    "import DashboardLayout from '@/components/layout/DashboardLayout';",
    "import { Activity, Save, Database, MonitorPlay, MousePointer2 } from 'lucide-react';",
    "import { Toaster, toast } from 'sonner';",
    "import { SHIFT_STYLES, SHIFT_HOURS_LOOKUP } from './constants';",
    "import { getDateKey, isDateLocked } from './utils';",
    "import { usePlanificacionLogic } from './usePlanificacionLogic';",
    "import { ShiftSelectorModal, RRHHModal } from './Modals';",
    "",
    "// 🛑 FIX: ASIGNACIÓN SEGURA DEL COMPONENTE LIST",
    "const List: any = dynamic(() => import('react-window').then((mod: any) => {",
    "    // Si mod.FixedSizeList existe, usalo. Si no, busca en default. Si no, usa un componente vacío para no romper.",
    "    return mod.FixedSizeList || mod.default?.FixedSizeList || (() => null);",
    "}), { ssr: false });",
    "",
    "const Row = ({ index, style, data }: any) => {",
    "    const { displayedEmployees, daysInMonth, shiftsMap, pendingChanges, absencesMap, selection, onCellInteraction } = data;",
    "    const emp = displayedEmployees[index]; if (!emp) return null;",
    "    return (",
    "        <div style={style} className='flex border-b border-slate-100 hover:bg-slate-50 transition-colors h-[50px]'>",
    "            <div className='w-[240px] shrink-0 sticky left-0 z-20 bg-white border-r flex items-center px-4 font-black text-[10px] uppercase truncate shadow-sm'> {emp.name} </div>",
    "            {daysInMonth.map((day: any, dIdx: number) => {",
    "                const dKey = getDateKey(day); const key = emp.id + '_' + dKey;",
    "                const s = shiftsMap[key]; const p = pendingChanges[key];",
    "                const isSel = selection.start && index >= Math.min(selection.start.r, selection.end.r) && index <= Math.max(selection.start.r, selection.end.r) && dIdx >= Math.min(selection.start.c, selection.end.c) && dIdx <= Math.max(selection.start.c, selection.end.c);",
    "                let content = s?.code || ''; let cls = SHIFT_STYLES[s?.code] || 'bg-white';",
    "                if (p) { if(p.isDeleted) content='X', cls='bg-rose-50'; else content=p.code, cls='bg-amber-100 font-bold ring-1 ring-amber-400'; }",
    "                if (absencesMap[key]) { content='V'; cls=SHIFT_STYLES['V']; }",
    "                return (",
    "                    <div key={key} onMouseDown={() => onCellInteraction('DOWN', index, dIdx)} onMouseEnter={() => onCellInteraction('ENTER', index, dIdx)}",
    "                         className={'w-[45px] shrink-0 border-r flex items-center justify-center cursor-pointer transition-all ' + (isSel ? 'bg-indigo-50' : '')}>",
    "                        <div className={'w-9 h-9 rounded-xl flex items-center justify-center text-[10px] font-black border shadow-sm ' + cls}> {content} </div>",
    "                    </div>",
    "                );",
    "            })}",
    "        </div>",
    "    );",
    "};",
    "",
    "export default function AuditPlanPage() {",
    "    const [mounted, setMounted] = useState(false);",
    "    const [currentDate, setCurrentDate] = useState(new Date());",
    "    const [selectedClient, setSelectedClient] = useState('');",
    "    const [selectedObjective, setSelectedObjective] = useState('');",
    "    const [selection, setSelection] = useState<any>({ start: null, end: null });",
    "    const [isDragging, setIsDragging] = useState(false);",
    "    const [selectedCell, setSelectedCell] = useState<any>(null);",
    "    const [activePosition, setActivePosition] = useState('General');",
    "    const [showRRHHModal, setShowRRHHModal] = useState(false);",
    "    const [rrhhData, setRrhhData] = useState({ type: 'Vacaciones', reason: '' });",
    "    useEffect(() => { setMounted(true); }, []);",
    "    const { employees, shiftsMap, absencesMap, clients, pendingChanges, setPendingChanges, isProcessing, positionStructure, handleSaveAll } = usePlanificacionLogic(selectedClient, selectedObjective, 'Supervisor');",
    "    const daysInMonth = useMemo(() => {",
    "        const d = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);",
    "        const days = []; while (d.getMonth() === currentDate.getMonth()) { days.push(new Date(d)); d.setDate(d.getDate() + 1); }",
    "        return days;",
    "    }, [currentDate]);",
    "    const displayedEmployees = useMemo(() => {",
    "        if(!selectedObjective) return [];",
    "        return [...employees].filter((e:any) => e.preferredObjectiveId === selectedObjective || Object.keys(shiftsMap).some(k => k.startsWith(e.id) && shiftsMap[k].objectiveId === selectedObjective)).sort((a:any, b:any) => a.name.localeCompare(b.name));",
    "    }, [employees, selectedObjective, shiftsMap]);",
    "    const onCellInteraction = (type: string, r: number, c: number) => {",
    "        if (type === 'DOWN') { setIsDragging(true); setSelection({ start: { r, c }, end: { r, c } }); }",
    "        else if (isDragging) { setSelection((prev: any) => ({ ...prev, end: { r, c } })); }",
    "    };",
    "    if (!mounted) return null;",
    "    return (",
    "        <DashboardLayout>",
    "            <Toaster position='top-center' richColors />",
    "            <div className='flex flex-col h-[calc(100vh-80px)] p-4 space-y-4 select-none' onMouseUp={() => { if(!isDragging) return; setIsDragging(false); if(selection.start && selection.start.r === selection.end.r && selection.start.c === selection.end.c) { const emp:any = displayedEmployees[selection.start.r]; setSelectedCell({ empId: emp.id, dateStr: getDateKey(daysInMonth[selection.start.c]) }); } }}>",
    "                <div className='bg-slate-900 text-white p-6 rounded-[2.5rem] shadow-2xl flex items-center justify-between border-b-4 border-indigo-500'>",
    "                    <div className='flex items-center gap-6'><Activity size={32}/><div><h1 className='text-2xl font-black italic'>CMD V8</h1></div></div>",
    "                    <div className='flex gap-4'>",
    "                        <div className='flex gap-2 bg-slate-800 p-2 rounded-2xl'>",
    "                            <select value={selectedClient} onChange={e => { setSelectedClient(e.target.value); setSelectedObjective(''); }} className='bg-transparent text-white text-xs font-bold outline-none'><option value=''>CLIENTE...</option>{clients.map((c:any) => <option key={c.id} value={c.id}>{c.name}</option>)}</select>",
    "                            <select value={selectedObjective} onChange={e => setSelectedObjective(e.target.value)} className='bg-transparent text-white text-xs font-bold outline-none'><option value=''>OBJETIVO...</option>{clients.find((c:any) => c.id === selectedClient)?.objetivos?.map((o:any) => <option key={o.id||o.name} value={o.id||o.name}>{o.name}</option>)}</select>",
    "                        </div>",
    "                        {Object.keys(pendingChanges).length > 0 && <button onClick={handleSaveAll} className='bg-emerald-500 px-8 py-3 rounded-2xl font-black shadow-lg'><Save/></button>}",
    "                    </div>",
    "                </div>",
    "                <div className='flex-1 bg-white rounded-[3rem] border shadow-2xl overflow-hidden flex flex-col'>",
    "                    <div className='flex bg-slate-50 h-14 border-b'><div className='w-[240px] shrink-0 border-r flex items-center px-6 font-black text-xs'>DOTACION ({displayedEmployees.length})</div><div className='flex overflow-hidden'>{daysInMonth.map(d => (<div key={d.toISOString()} className='w-[45px] border-r flex flex-col items-center justify-center'><span className='text-[8px] font-bold'>{['D','L','M','X','J','V','S'][d.getDay()]}</span><span className='text-xs font-black'>{d.getDate()}</span></div>))}</div></div>",
    "                    <div className='flex-1 overflow-x-auto'>",
    "                        <div style={{ width: 240 + (daysInMonth.length * 45) }}>",
    "                            {selectedObjective ? (",
    "                                <List height={550} itemCount={displayedEmployees.length} itemSize={50} width='100%' itemData={{ displayedEmployees, daysInMonth, shiftsMap, pendingChanges, absencesMap, selection, onCellInteraction }}>{Row}</List>",
    "                            ) : <div className='h-[400px] flex items-center justify-center font-black text-slate-300'>SELECCIONE OBJETIVO</div>}",
    "                        </div>",
    "                    </div>",
    "                </div>",
    "                <ShiftSelectorModal selectedCell={selectedCell} employees={employees} positionStructure={positionStructure} activePosition={activePosition} setActivePosition={setActivePosition} onAssign={(code:any) => { setPendingChanges((prev:any) => ({...prev, [selectedCell.empId + '_' + selectedCell.dateStr]: { code, hours: SHIFT_HOURS_LOOKUP[code], positionName: activePosition }})); setSelectedCell(null); }} onDelete={() => { setPendingChanges((prev:any) => ({...prev, [selectedCell.empId + '_' + selectedCell.dateStr]: { isDeleted: true }})); setSelectedCell(null); }} onRRHH={() => setShowRRHHModal(true)} onClose={() => setSelectedCell(null)} />",
    "                {showRRHHModal && <RRHHModal onSubmit={() => { toast.success('OK'); setShowRRHHModal(false); setSelectedCell(null); }} onClose={() => setShowRRHHModal(false)} />}",
    "            </div>",
    "            <style jsx global>{\` .custom-scrollbar::-webkit-scrollbar { width: 8px; height: 8px; } .custom-scrollbar::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 10px; } \`}</style>",
    "        </DashboardLayout>",
    "    );",
    "}"
]);

console.log('\n🏆 FIX V8: List Component Seguro + Import Modals OK.');